#include <iostream>
#include "SmartTile.h"

using namespace std;

int main() {
    //
//
// Start of auto-generated SAMChess code
//
// Generated by /Users/ethan/Developer/PycharmProjects/SAMChess_macros/board_init.py
// on 2016-02-21T20:44:41.493716
//
//
    SAMClib::SmartTile tiles[8][8];

    SAMClib::SmartTile nulltile;
    nulltile.n = nulltile.self;
    nulltile.ne = nulltile.self;
    nulltile.e = nulltile.self;
    nulltile.se = nulltile.self;
    nulltile.s = nulltile.self;
    nulltile.sw = nulltile.self;
    nulltile.w = nulltile.self;
    nulltile.nw = nulltile.self;

// Generating the board


// init (step 1) for row 0:
    tiles[0][0] = SAMClib::SmartTile();                    // init (step 1) for col 0:
    tiles[0][1] = SAMClib::SmartTile();                    // init (step 1) for col 1:
    tiles[0][2] = SAMClib::SmartTile();                    // init (step 1) for col 2:
    tiles[0][3] = SAMClib::SmartTile();                    // init (step 1) for col 3:
    tiles[0][4] = SAMClib::SmartTile();                    // init (step 1) for col 4:
    tiles[0][5] = SAMClib::SmartTile();                    // init (step 1) for col 5:
    tiles[0][6] = SAMClib::SmartTile();                    // init (step 1) for col 6:
    tiles[0][7] = SAMClib::SmartTile();                    // init (step 1) for col 7:

// init (step 1) for row 1:
    tiles[1][0] = SAMClib::SmartTile();                    // init (step 1) for col 0:
    tiles[1][1] = SAMClib::SmartTile();                    // init (step 1) for col 1:
    tiles[1][2] = SAMClib::SmartTile();                    // init (step 1) for col 2:
    tiles[1][3] = SAMClib::SmartTile();                    // init (step 1) for col 3:
    tiles[1][4] = SAMClib::SmartTile();                    // init (step 1) for col 4:
    tiles[1][5] = SAMClib::SmartTile();                    // init (step 1) for col 5:
    tiles[1][6] = SAMClib::SmartTile();                    // init (step 1) for col 6:
    tiles[1][7] = SAMClib::SmartTile();                    // init (step 1) for col 7:

// init (step 1) for row 2:
    tiles[2][0] = SAMClib::SmartTile();                    // init (step 1) for col 0:
    tiles[2][1] = SAMClib::SmartTile();                    // init (step 1) for col 1:
    tiles[2][2] = SAMClib::SmartTile();                    // init (step 1) for col 2:
    tiles[2][3] = SAMClib::SmartTile();                    // init (step 1) for col 3:
    tiles[2][4] = SAMClib::SmartTile();                    // init (step 1) for col 4:
    tiles[2][5] = SAMClib::SmartTile();                    // init (step 1) for col 5:
    tiles[2][6] = SAMClib::SmartTile();                    // init (step 1) for col 6:
    tiles[2][7] = SAMClib::SmartTile();                    // init (step 1) for col 7:

// init (step 1) for row 3:
    tiles[3][0] = SAMClib::SmartTile();                    // init (step 1) for col 0:
    tiles[3][1] = SAMClib::SmartTile();                    // init (step 1) for col 1:
    tiles[3][2] = SAMClib::SmartTile();                    // init (step 1) for col 2:
    tiles[3][3] = SAMClib::SmartTile();                    // init (step 1) for col 3:
    tiles[3][4] = SAMClib::SmartTile();                    // init (step 1) for col 4:
    tiles[3][5] = SAMClib::SmartTile();                    // init (step 1) for col 5:
    tiles[3][6] = SAMClib::SmartTile();                    // init (step 1) for col 6:
    tiles[3][7] = SAMClib::SmartTile();                    // init (step 1) for col 7:

// init (step 1) for row 4:
    tiles[4][0] = SAMClib::SmartTile();                    // init (step 1) for col 0:
    tiles[4][1] = SAMClib::SmartTile();                    // init (step 1) for col 1:
    tiles[4][2] = SAMClib::SmartTile();                    // init (step 1) for col 2:
    tiles[4][3] = SAMClib::SmartTile();                    // init (step 1) for col 3:
    tiles[4][4] = SAMClib::SmartTile();                    // init (step 1) for col 4:
    tiles[4][5] = SAMClib::SmartTile();                    // init (step 1) for col 5:
    tiles[4][6] = SAMClib::SmartTile();                    // init (step 1) for col 6:
    tiles[4][7] = SAMClib::SmartTile();                    // init (step 1) for col 7:

// init (step 1) for row 5:
    tiles[5][0] = SAMClib::SmartTile();                    // init (step 1) for col 0:
    tiles[5][1] = SAMClib::SmartTile();                    // init (step 1) for col 1:
    tiles[5][2] = SAMClib::SmartTile();                    // init (step 1) for col 2:
    tiles[5][3] = SAMClib::SmartTile();                    // init (step 1) for col 3:
    tiles[5][4] = SAMClib::SmartTile();                    // init (step 1) for col 4:
    tiles[5][5] = SAMClib::SmartTile();                    // init (step 1) for col 5:
    tiles[5][6] = SAMClib::SmartTile();                    // init (step 1) for col 6:
    tiles[5][7] = SAMClib::SmartTile();                    // init (step 1) for col 7:

// init (step 1) for row 6:
    tiles[6][0] = SAMClib::SmartTile();                    // init (step 1) for col 0:
    tiles[6][1] = SAMClib::SmartTile();                    // init (step 1) for col 1:
    tiles[6][2] = SAMClib::SmartTile();                    // init (step 1) for col 2:
    tiles[6][3] = SAMClib::SmartTile();                    // init (step 1) for col 3:
    tiles[6][4] = SAMClib::SmartTile();                    // init (step 1) for col 4:
    tiles[6][5] = SAMClib::SmartTile();                    // init (step 1) for col 5:
    tiles[6][6] = SAMClib::SmartTile();                    // init (step 1) for col 6:
    tiles[6][7] = SAMClib::SmartTile();                    // init (step 1) for col 7:

// init (step 1) for row 7:
    tiles[7][0] = SAMClib::SmartTile();                    // init (step 1) for col 0:
    tiles[7][1] = SAMClib::SmartTile();                    // init (step 1) for col 1:
    tiles[7][2] = SAMClib::SmartTile();                    // init (step 1) for col 2:
    tiles[7][3] = SAMClib::SmartTile();                    // init (step 1) for col 3:
    tiles[7][4] = SAMClib::SmartTile();                    // init (step 1) for col 4:
    tiles[7][5] = SAMClib::SmartTile();                    // init (step 1) for col 5:
    tiles[7][6] = SAMClib::SmartTile();                    // init (step 1) for col 6:
    tiles[7][7] = SAMClib::SmartTile();                    // init (step 1) for col 7:
//
// Stitch the linked-list
//
// init (step 2) for row 0:

    //
    // stitch (init step 2) for [ ROW 0 | COL 0 ]:
    //
    tiles[0][0].n = nulltile.self;
    tiles[0][0].ne = nulltile.self;
    tiles[0][0].e = tiles[0][1].self;                      // stitch # 0 --> # 1
    tiles[0][0].se = tiles[1][1].self;                     // stitch # 0 --> # 9
    tiles[0][0].s = tiles[1][0].self;                      // stitch # 0 --> # 8
    tiles[0][0].sw = nulltile.self;
    tiles[0][0].w = nulltile.self;
    tiles[0][0].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 0 | COL 1 ]:
    //
    tiles[0][1].n = nulltile.self;
    tiles[0][1].ne = nulltile.self;
    tiles[0][1].e = tiles[0][2].self;                      // stitch # 1 --> # 2
    tiles[0][1].se = tiles[1][2].self;                     // stitch # 1 --> # 10
    tiles[0][1].s = tiles[1][1].self;                      // stitch # 1 --> # 9
    tiles[0][1].sw = tiles[1][0].self;                     // stitch # 1 --> # 8
    tiles[0][1].w = tiles[0][0].self;                      // stitch # 1 --> # 0
    tiles[0][1].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 0 | COL 2 ]:
    //
    tiles[0][2].n = nulltile.self;
    tiles[0][2].ne = nulltile.self;
    tiles[0][2].e = tiles[0][3].self;                      // stitch # 2 --> # 3
    tiles[0][2].se = tiles[1][3].self;                     // stitch # 2 --> # 11
    tiles[0][2].s = tiles[1][2].self;                      // stitch # 2 --> # 10
    tiles[0][2].sw = tiles[1][1].self;                     // stitch # 2 --> # 9
    tiles[0][2].w = tiles[0][1].self;                      // stitch # 2 --> # 1
    tiles[0][2].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 0 | COL 3 ]:
    //
    tiles[0][3].n = nulltile.self;
    tiles[0][3].ne = nulltile.self;
    tiles[0][3].e = tiles[0][4].self;                      // stitch # 3 --> # 4
    tiles[0][3].se = tiles[1][4].self;                     // stitch # 3 --> # 12
    tiles[0][3].s = tiles[1][3].self;                      // stitch # 3 --> # 11
    tiles[0][3].sw = tiles[1][2].self;                     // stitch # 3 --> # 10
    tiles[0][3].w = tiles[0][2].self;                      // stitch # 3 --> # 2
    tiles[0][3].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 0 | COL 4 ]:
    //
    tiles[0][4].n = nulltile.self;
    tiles[0][4].ne = nulltile.self;
    tiles[0][4].e = tiles[0][5].self;                      // stitch # 4 --> # 5
    tiles[0][4].se = tiles[1][5].self;                     // stitch # 4 --> # 13
    tiles[0][4].s = tiles[1][4].self;                      // stitch # 4 --> # 12
    tiles[0][4].sw = tiles[1][3].self;                     // stitch # 4 --> # 11
    tiles[0][4].w = tiles[0][3].self;                      // stitch # 4 --> # 3
    tiles[0][4].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 0 | COL 5 ]:
    //
    tiles[0][5].n = nulltile.self;
    tiles[0][5].ne = nulltile.self;
    tiles[0][5].e = tiles[0][6].self;                      // stitch # 5 --> # 6
    tiles[0][5].se = tiles[1][6].self;                     // stitch # 5 --> # 14
    tiles[0][5].s = tiles[1][5].self;                      // stitch # 5 --> # 13
    tiles[0][5].sw = tiles[1][4].self;                     // stitch # 5 --> # 12
    tiles[0][5].w = tiles[0][4].self;                      // stitch # 5 --> # 4
    tiles[0][5].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 0 | COL 6 ]:
    //
    tiles[0][6].n = nulltile.self;
    tiles[0][6].ne = nulltile.self;
    tiles[0][6].e = tiles[0][7].self;                      // stitch # 6 --> # 7
    tiles[0][6].se = tiles[1][7].self;                     // stitch # 6 --> # 15
    tiles[0][6].s = tiles[1][6].self;                      // stitch # 6 --> # 14
    tiles[0][6].sw = tiles[1][5].self;                     // stitch # 6 --> # 13
    tiles[0][6].w = tiles[0][5].self;                      // stitch # 6 --> # 5
    tiles[0][6].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 0 | COL 7 ]:
    //
    tiles[0][7].n = nulltile.self;
    tiles[0][7].ne = nulltile.self;
    tiles[0][7].e = nulltile.self;
    tiles[0][7].se = nulltile.self;
    tiles[0][7].s = tiles[1][7].self;                      // stitch # 7 --> # 15
    tiles[0][7].sw = tiles[1][6].self;                     // stitch # 7 --> # 14
    tiles[0][7].w = tiles[0][6].self;                      // stitch # 7 --> # 6
    tiles[0][7].nw = nulltile.self;
// init (step 2) for row 1:

    //
    // stitch (init step 2) for [ ROW 1 | COL 0 ]:
    //
    tiles[1][0].n = tiles[0][0].self;                      // stitch # 8 --> # 0
    tiles[1][0].ne = tiles[0][1].self;                     // stitch # 8 --> # 1
    tiles[1][0].e = tiles[1][1].self;                      // stitch # 8 --> # 9
    tiles[1][0].se = tiles[2][1].self;                     // stitch # 8 --> # 17
    tiles[1][0].s = tiles[2][0].self;                      // stitch # 8 --> # 16
    tiles[1][0].sw = nulltile.self;
    tiles[1][0].w = nulltile.self;
    tiles[1][0].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 1 | COL 1 ]:
    //
    tiles[1][1].n = tiles[0][1].self;                      // stitch # 9 --> # 1
    tiles[1][1].ne = tiles[0][2].self;                     // stitch # 9 --> # 2
    tiles[1][1].e = tiles[1][2].self;                      // stitch # 9 --> # 10
    tiles[1][1].se = tiles[2][2].self;                     // stitch # 9 --> # 18
    tiles[1][1].s = tiles[2][1].self;                      // stitch # 9 --> # 17
    tiles[1][1].sw = tiles[2][0].self;                     // stitch # 9 --> # 16
    tiles[1][1].w = tiles[1][0].self;                      // stitch # 9 --> # 8
    tiles[1][1].nw = tiles[0][0].self;                     // stitch # 9 --> # 0

    //
    // stitch (init step 2) for [ ROW 1 | COL 2 ]:
    //
    tiles[1][2].n = tiles[0][2].self;                      // stitch # 10 --> # 2
    tiles[1][2].ne = tiles[0][3].self;                     // stitch # 10 --> # 3
    tiles[1][2].e = tiles[1][3].self;                      // stitch # 10 --> # 11
    tiles[1][2].se = tiles[2][3].self;                     // stitch # 10 --> # 19
    tiles[1][2].s = tiles[2][2].self;                      // stitch # 10 --> # 18
    tiles[1][2].sw = tiles[2][1].self;                     // stitch # 10 --> # 17
    tiles[1][2].w = tiles[1][1].self;                      // stitch # 10 --> # 9
    tiles[1][2].nw = tiles[0][1].self;                     // stitch # 10 --> # 1

    //
    // stitch (init step 2) for [ ROW 1 | COL 3 ]:
    //
    tiles[1][3].n = tiles[0][3].self;                      // stitch # 11 --> # 3
    tiles[1][3].ne = tiles[0][4].self;                     // stitch # 11 --> # 4
    tiles[1][3].e = tiles[1][4].self;                      // stitch # 11 --> # 12
    tiles[1][3].se = tiles[2][4].self;                     // stitch # 11 --> # 20
    tiles[1][3].s = tiles[2][3].self;                      // stitch # 11 --> # 19
    tiles[1][3].sw = tiles[2][2].self;                     // stitch # 11 --> # 18
    tiles[1][3].w = tiles[1][2].self;                      // stitch # 11 --> # 10
    tiles[1][3].nw = tiles[0][2].self;                     // stitch # 11 --> # 2

    //
    // stitch (init step 2) for [ ROW 1 | COL 4 ]:
    //
    tiles[1][4].n = tiles[0][4].self;                      // stitch # 12 --> # 4
    tiles[1][4].ne = tiles[0][5].self;                     // stitch # 12 --> # 5
    tiles[1][4].e = tiles[1][5].self;                      // stitch # 12 --> # 13
    tiles[1][4].se = tiles[2][5].self;                     // stitch # 12 --> # 21
    tiles[1][4].s = tiles[2][4].self;                      // stitch # 12 --> # 20
    tiles[1][4].sw = tiles[2][3].self;                     // stitch # 12 --> # 19
    tiles[1][4].w = tiles[1][3].self;                      // stitch # 12 --> # 11
    tiles[1][4].nw = tiles[0][3].self;                     // stitch # 12 --> # 3

    //
    // stitch (init step 2) for [ ROW 1 | COL 5 ]:
    //
    tiles[1][5].n = tiles[0][5].self;                      // stitch # 13 --> # 5
    tiles[1][5].ne = tiles[0][6].self;                     // stitch # 13 --> # 6
    tiles[1][5].e = tiles[1][6].self;                      // stitch # 13 --> # 14
    tiles[1][5].se = tiles[2][6].self;                     // stitch # 13 --> # 22
    tiles[1][5].s = tiles[2][5].self;                      // stitch # 13 --> # 21
    tiles[1][5].sw = tiles[2][4].self;                     // stitch # 13 --> # 20
    tiles[1][5].w = tiles[1][4].self;                      // stitch # 13 --> # 12
    tiles[1][5].nw = tiles[0][4].self;                     // stitch # 13 --> # 4

    //
    // stitch (init step 2) for [ ROW 1 | COL 6 ]:
    //
    tiles[1][6].n = tiles[0][6].self;                      // stitch # 14 --> # 6
    tiles[1][6].ne = tiles[0][7].self;                     // stitch # 14 --> # 7
    tiles[1][6].e = tiles[1][7].self;                      // stitch # 14 --> # 15
    tiles[1][6].se = tiles[2][7].self;                     // stitch # 14 --> # 23
    tiles[1][6].s = tiles[2][6].self;                      // stitch # 14 --> # 22
    tiles[1][6].sw = tiles[2][5].self;                     // stitch # 14 --> # 21
    tiles[1][6].w = tiles[1][5].self;                      // stitch # 14 --> # 13
    tiles[1][6].nw = tiles[0][5].self;                     // stitch # 14 --> # 5

    //
    // stitch (init step 2) for [ ROW 1 | COL 7 ]:
    //
    tiles[1][7].n = tiles[0][7].self;                      // stitch # 15 --> # 7
    tiles[1][7].ne = nulltile.self;
    tiles[1][7].e = nulltile.self;
    tiles[1][7].se = nulltile.self;
    tiles[1][7].s = tiles[2][7].self;                      // stitch # 15 --> # 23
    tiles[1][7].sw = tiles[2][6].self;                     // stitch # 15 --> # 22
    tiles[1][7].w = tiles[1][6].self;                      // stitch # 15 --> # 14
    tiles[1][7].nw = tiles[0][6].self;                     // stitch # 15 --> # 6
// init (step 2) for row 2:

    //
    // stitch (init step 2) for [ ROW 2 | COL 0 ]:
    //
    tiles[2][0].n = tiles[1][0].self;                      // stitch # 16 --> # 8
    tiles[2][0].ne = tiles[1][1].self;                     // stitch # 16 --> # 9
    tiles[2][0].e = tiles[2][1].self;                      // stitch # 16 --> # 17
    tiles[2][0].se = tiles[3][1].self;                     // stitch # 16 --> # 25
    tiles[2][0].s = tiles[3][0].self;                      // stitch # 16 --> # 24
    tiles[2][0].sw = nulltile.self;
    tiles[2][0].w = nulltile.self;
    tiles[2][0].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 2 | COL 1 ]:
    //
    tiles[2][1].n = tiles[1][1].self;                      // stitch # 17 --> # 9
    tiles[2][1].ne = tiles[1][2].self;                     // stitch # 17 --> # 10
    tiles[2][1].e = tiles[2][2].self;                      // stitch # 17 --> # 18
    tiles[2][1].se = tiles[3][2].self;                     // stitch # 17 --> # 26
    tiles[2][1].s = tiles[3][1].self;                      // stitch # 17 --> # 25
    tiles[2][1].sw = tiles[3][0].self;                     // stitch # 17 --> # 24
    tiles[2][1].w = tiles[2][0].self;                      // stitch # 17 --> # 16
    tiles[2][1].nw = tiles[1][0].self;                     // stitch # 17 --> # 8

    //
    // stitch (init step 2) for [ ROW 2 | COL 2 ]:
    //
    tiles[2][2].n = tiles[1][2].self;                      // stitch # 18 --> # 10
    tiles[2][2].ne = tiles[1][3].self;                     // stitch # 18 --> # 11
    tiles[2][2].e = tiles[2][3].self;                      // stitch # 18 --> # 19
    tiles[2][2].se = tiles[3][3].self;                     // stitch # 18 --> # 27
    tiles[2][2].s = tiles[3][2].self;                      // stitch # 18 --> # 26
    tiles[2][2].sw = tiles[3][1].self;                     // stitch # 18 --> # 25
    tiles[2][2].w = tiles[2][1].self;                      // stitch # 18 --> # 17
    tiles[2][2].nw = tiles[1][1].self;                     // stitch # 18 --> # 9

    //
    // stitch (init step 2) for [ ROW 2 | COL 3 ]:
    //
    tiles[2][3].n = tiles[1][3].self;                      // stitch # 19 --> # 11
    tiles[2][3].ne = tiles[1][4].self;                     // stitch # 19 --> # 12
    tiles[2][3].e = tiles[2][4].self;                      // stitch # 19 --> # 20
    tiles[2][3].se = tiles[3][4].self;                     // stitch # 19 --> # 28
    tiles[2][3].s = tiles[3][3].self;                      // stitch # 19 --> # 27
    tiles[2][3].sw = tiles[3][2].self;                     // stitch # 19 --> # 26
    tiles[2][3].w = tiles[2][2].self;                      // stitch # 19 --> # 18
    tiles[2][3].nw = tiles[1][2].self;                     // stitch # 19 --> # 10

    //
    // stitch (init step 2) for [ ROW 2 | COL 4 ]:
    //
    tiles[2][4].n = tiles[1][4].self;                      // stitch # 20 --> # 12
    tiles[2][4].ne = tiles[1][5].self;                     // stitch # 20 --> # 13
    tiles[2][4].e = tiles[2][5].self;                      // stitch # 20 --> # 21
    tiles[2][4].se = tiles[3][5].self;                     // stitch # 20 --> # 29
    tiles[2][4].s = tiles[3][4].self;                      // stitch # 20 --> # 28
    tiles[2][4].sw = tiles[3][3].self;                     // stitch # 20 --> # 27
    tiles[2][4].w = tiles[2][3].self;                      // stitch # 20 --> # 19
    tiles[2][4].nw = tiles[1][3].self;                     // stitch # 20 --> # 11

    //
    // stitch (init step 2) for [ ROW 2 | COL 5 ]:
    //
    tiles[2][5].n = tiles[1][5].self;                      // stitch # 21 --> # 13
    tiles[2][5].ne = tiles[1][6].self;                     // stitch # 21 --> # 14
    tiles[2][5].e = tiles[2][6].self;                      // stitch # 21 --> # 22
    tiles[2][5].se = tiles[3][6].self;                     // stitch # 21 --> # 30
    tiles[2][5].s = tiles[3][5].self;                      // stitch # 21 --> # 29
    tiles[2][5].sw = tiles[3][4].self;                     // stitch # 21 --> # 28
    tiles[2][5].w = tiles[2][4].self;                      // stitch # 21 --> # 20
    tiles[2][5].nw = tiles[1][4].self;                     // stitch # 21 --> # 12

    //
    // stitch (init step 2) for [ ROW 2 | COL 6 ]:
    //
    tiles[2][6].n = tiles[1][6].self;                      // stitch # 22 --> # 14
    tiles[2][6].ne = tiles[1][7].self;                     // stitch # 22 --> # 15
    tiles[2][6].e = tiles[2][7].self;                      // stitch # 22 --> # 23
    tiles[2][6].se = tiles[3][7].self;                     // stitch # 22 --> # 31
    tiles[2][6].s = tiles[3][6].self;                      // stitch # 22 --> # 30
    tiles[2][6].sw = tiles[3][5].self;                     // stitch # 22 --> # 29
    tiles[2][6].w = tiles[2][5].self;                      // stitch # 22 --> # 21
    tiles[2][6].nw = tiles[1][5].self;                     // stitch # 22 --> # 13

    //
    // stitch (init step 2) for [ ROW 2 | COL 7 ]:
    //
    tiles[2][7].n = tiles[1][7].self;                      // stitch # 23 --> # 15
    tiles[2][7].ne = nulltile.self;
    tiles[2][7].e = nulltile.self;
    tiles[2][7].se = nulltile.self;
    tiles[2][7].s = tiles[3][7].self;                      // stitch # 23 --> # 31
    tiles[2][7].sw = tiles[3][6].self;                     // stitch # 23 --> # 30
    tiles[2][7].w = tiles[2][6].self;                      // stitch # 23 --> # 22
    tiles[2][7].nw = tiles[1][6].self;                     // stitch # 23 --> # 14
// init (step 2) for row 3:

    //
    // stitch (init step 2) for [ ROW 3 | COL 0 ]:
    //
    tiles[3][0].n = tiles[2][0].self;                      // stitch # 24 --> # 16
    tiles[3][0].ne = tiles[2][1].self;                     // stitch # 24 --> # 17
    tiles[3][0].e = tiles[3][1].self;                      // stitch # 24 --> # 25
    tiles[3][0].se = tiles[4][1].self;                     // stitch # 24 --> # 33
    tiles[3][0].s = tiles[4][0].self;                      // stitch # 24 --> # 32
    tiles[3][0].sw = nulltile.self;
    tiles[3][0].w = nulltile.self;
    tiles[3][0].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 3 | COL 1 ]:
    //
    tiles[3][1].n = tiles[2][1].self;                      // stitch # 25 --> # 17
    tiles[3][1].ne = tiles[2][2].self;                     // stitch # 25 --> # 18
    tiles[3][1].e = tiles[3][2].self;                      // stitch # 25 --> # 26
    tiles[3][1].se = tiles[4][2].self;                     // stitch # 25 --> # 34
    tiles[3][1].s = tiles[4][1].self;                      // stitch # 25 --> # 33
    tiles[3][1].sw = tiles[4][0].self;                     // stitch # 25 --> # 32
    tiles[3][1].w = tiles[3][0].self;                      // stitch # 25 --> # 24
    tiles[3][1].nw = tiles[2][0].self;                     // stitch # 25 --> # 16

    //
    // stitch (init step 2) for [ ROW 3 | COL 2 ]:
    //
    tiles[3][2].n = tiles[2][2].self;                      // stitch # 26 --> # 18
    tiles[3][2].ne = tiles[2][3].self;                     // stitch # 26 --> # 19
    tiles[3][2].e = tiles[3][3].self;                      // stitch # 26 --> # 27
    tiles[3][2].se = tiles[4][3].self;                     // stitch # 26 --> # 35
    tiles[3][2].s = tiles[4][2].self;                      // stitch # 26 --> # 34
    tiles[3][2].sw = tiles[4][1].self;                     // stitch # 26 --> # 33
    tiles[3][2].w = tiles[3][1].self;                      // stitch # 26 --> # 25
    tiles[3][2].nw = tiles[2][1].self;                     // stitch # 26 --> # 17

    //
    // stitch (init step 2) for [ ROW 3 | COL 3 ]:
    //
    tiles[3][3].n = tiles[2][3].self;                      // stitch # 27 --> # 19
    tiles[3][3].ne = tiles[2][4].self;                     // stitch # 27 --> # 20
    tiles[3][3].e = tiles[3][4].self;                      // stitch # 27 --> # 28
    tiles[3][3].se = tiles[4][4].self;                     // stitch # 27 --> # 36
    tiles[3][3].s = tiles[4][3].self;                      // stitch # 27 --> # 35
    tiles[3][3].sw = tiles[4][2].self;                     // stitch # 27 --> # 34
    tiles[3][3].w = tiles[3][2].self;                      // stitch # 27 --> # 26
    tiles[3][3].nw = tiles[2][2].self;                     // stitch # 27 --> # 18

    //
    // stitch (init step 2) for [ ROW 3 | COL 4 ]:
    //
    tiles[3][4].n = tiles[2][4].self;                      // stitch # 28 --> # 20
    tiles[3][4].ne = tiles[2][5].self;                     // stitch # 28 --> # 21
    tiles[3][4].e = tiles[3][5].self;                      // stitch # 28 --> # 29
    tiles[3][4].se = tiles[4][5].self;                     // stitch # 28 --> # 37
    tiles[3][4].s = tiles[4][4].self;                      // stitch # 28 --> # 36
    tiles[3][4].sw = tiles[4][3].self;                     // stitch # 28 --> # 35
    tiles[3][4].w = tiles[3][3].self;                      // stitch # 28 --> # 27
    tiles[3][4].nw = tiles[2][3].self;                     // stitch # 28 --> # 19

    //
    // stitch (init step 2) for [ ROW 3 | COL 5 ]:
    //
    tiles[3][5].n = tiles[2][5].self;                      // stitch # 29 --> # 21
    tiles[3][5].ne = tiles[2][6].self;                     // stitch # 29 --> # 22
    tiles[3][5].e = tiles[3][6].self;                      // stitch # 29 --> # 30
    tiles[3][5].se = tiles[4][6].self;                     // stitch # 29 --> # 38
    tiles[3][5].s = tiles[4][5].self;                      // stitch # 29 --> # 37
    tiles[3][5].sw = tiles[4][4].self;                     // stitch # 29 --> # 36
    tiles[3][5].w = tiles[3][4].self;                      // stitch # 29 --> # 28
    tiles[3][5].nw = tiles[2][4].self;                     // stitch # 29 --> # 20

    //
    // stitch (init step 2) for [ ROW 3 | COL 6 ]:
    //
    tiles[3][6].n = tiles[2][6].self;                      // stitch # 30 --> # 22
    tiles[3][6].ne = tiles[2][7].self;                     // stitch # 30 --> # 23
    tiles[3][6].e = tiles[3][7].self;                      // stitch # 30 --> # 31
    tiles[3][6].se = tiles[4][7].self;                     // stitch # 30 --> # 39
    tiles[3][6].s = tiles[4][6].self;                      // stitch # 30 --> # 38
    tiles[3][6].sw = tiles[4][5].self;                     // stitch # 30 --> # 37
    tiles[3][6].w = tiles[3][5].self;                      // stitch # 30 --> # 29
    tiles[3][6].nw = tiles[2][5].self;                     // stitch # 30 --> # 21

    //
    // stitch (init step 2) for [ ROW 3 | COL 7 ]:
    //
    tiles[3][7].n = tiles[2][7].self;                      // stitch # 31 --> # 23
    tiles[3][7].ne = nulltile.self;
    tiles[3][7].e = nulltile.self;
    tiles[3][7].se = nulltile.self;
    tiles[3][7].s = tiles[4][7].self;                      // stitch # 31 --> # 39
    tiles[3][7].sw = tiles[4][6].self;                     // stitch # 31 --> # 38
    tiles[3][7].w = tiles[3][6].self;                      // stitch # 31 --> # 30
    tiles[3][7].nw = tiles[2][6].self;                     // stitch # 31 --> # 22
// init (step 2) for row 4:

    //
    // stitch (init step 2) for [ ROW 4 | COL 0 ]:
    //
    tiles[4][0].n = tiles[3][0].self;                      // stitch # 32 --> # 24
    tiles[4][0].ne = tiles[3][1].self;                     // stitch # 32 --> # 25
    tiles[4][0].e = tiles[4][1].self;                      // stitch # 32 --> # 33
    tiles[4][0].se = tiles[5][1].self;                     // stitch # 32 --> # 41
    tiles[4][0].s = tiles[5][0].self;                      // stitch # 32 --> # 40
    tiles[4][0].sw = nulltile.self;
    tiles[4][0].w = nulltile.self;
    tiles[4][0].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 4 | COL 1 ]:
    //
    tiles[4][1].n = tiles[3][1].self;                      // stitch # 33 --> # 25
    tiles[4][1].ne = tiles[3][2].self;                     // stitch # 33 --> # 26
    tiles[4][1].e = tiles[4][2].self;                      // stitch # 33 --> # 34
    tiles[4][1].se = tiles[5][2].self;                     // stitch # 33 --> # 42
    tiles[4][1].s = tiles[5][1].self;                      // stitch # 33 --> # 41
    tiles[4][1].sw = tiles[5][0].self;                     // stitch # 33 --> # 40
    tiles[4][1].w = tiles[4][0].self;                      // stitch # 33 --> # 32
    tiles[4][1].nw = tiles[3][0].self;                     // stitch # 33 --> # 24

    //
    // stitch (init step 2) for [ ROW 4 | COL 2 ]:
    //
    tiles[4][2].n = tiles[3][2].self;                      // stitch # 34 --> # 26
    tiles[4][2].ne = tiles[3][3].self;                     // stitch # 34 --> # 27
    tiles[4][2].e = tiles[4][3].self;                      // stitch # 34 --> # 35
    tiles[4][2].se = tiles[5][3].self;                     // stitch # 34 --> # 43
    tiles[4][2].s = tiles[5][2].self;                      // stitch # 34 --> # 42
    tiles[4][2].sw = tiles[5][1].self;                     // stitch # 34 --> # 41
    tiles[4][2].w = tiles[4][1].self;                      // stitch # 34 --> # 33
    tiles[4][2].nw = tiles[3][1].self;                     // stitch # 34 --> # 25

    //
    // stitch (init step 2) for [ ROW 4 | COL 3 ]:
    //
    tiles[4][3].n = tiles[3][3].self;                      // stitch # 35 --> # 27
    tiles[4][3].ne = tiles[3][4].self;                     // stitch # 35 --> # 28
    tiles[4][3].e = tiles[4][4].self;                      // stitch # 35 --> # 36
    tiles[4][3].se = tiles[5][4].self;                     // stitch # 35 --> # 44
    tiles[4][3].s = tiles[5][3].self;                      // stitch # 35 --> # 43
    tiles[4][3].sw = tiles[5][2].self;                     // stitch # 35 --> # 42
    tiles[4][3].w = tiles[4][2].self;                      // stitch # 35 --> # 34
    tiles[4][3].nw = tiles[3][2].self;                     // stitch # 35 --> # 26

    //
    // stitch (init step 2) for [ ROW 4 | COL 4 ]:
    //
    tiles[4][4].n = tiles[3][4].self;                      // stitch # 36 --> # 28
    tiles[4][4].ne = tiles[3][5].self;                     // stitch # 36 --> # 29
    tiles[4][4].e = tiles[4][5].self;                      // stitch # 36 --> # 37
    tiles[4][4].se = tiles[5][5].self;                     // stitch # 36 --> # 45
    tiles[4][4].s = tiles[5][4].self;                      // stitch # 36 --> # 44
    tiles[4][4].sw = tiles[5][3].self;                     // stitch # 36 --> # 43
    tiles[4][4].w = tiles[4][3].self;                      // stitch # 36 --> # 35
    tiles[4][4].nw = tiles[3][3].self;                     // stitch # 36 --> # 27

    //
    // stitch (init step 2) for [ ROW 4 | COL 5 ]:
    //
    tiles[4][5].n = tiles[3][5].self;                      // stitch # 37 --> # 29
    tiles[4][5].ne = tiles[3][6].self;                     // stitch # 37 --> # 30
    tiles[4][5].e = tiles[4][6].self;                      // stitch # 37 --> # 38
    tiles[4][5].se = tiles[5][6].self;                     // stitch # 37 --> # 46
    tiles[4][5].s = tiles[5][5].self;                      // stitch # 37 --> # 45
    tiles[4][5].sw = tiles[5][4].self;                     // stitch # 37 --> # 44
    tiles[4][5].w = tiles[4][4].self;                      // stitch # 37 --> # 36
    tiles[4][5].nw = tiles[3][4].self;                     // stitch # 37 --> # 28

    //
    // stitch (init step 2) for [ ROW 4 | COL 6 ]:
    //
    tiles[4][6].n = tiles[3][6].self;                      // stitch # 38 --> # 30
    tiles[4][6].ne = tiles[3][7].self;                     // stitch # 38 --> # 31
    tiles[4][6].e = tiles[4][7].self;                      // stitch # 38 --> # 39
    tiles[4][6].se = tiles[5][7].self;                     // stitch # 38 --> # 47
    tiles[4][6].s = tiles[5][6].self;                      // stitch # 38 --> # 46
    tiles[4][6].sw = tiles[5][5].self;                     // stitch # 38 --> # 45
    tiles[4][6].w = tiles[4][5].self;                      // stitch # 38 --> # 37
    tiles[4][6].nw = tiles[3][5].self;                     // stitch # 38 --> # 29

    //
    // stitch (init step 2) for [ ROW 4 | COL 7 ]:
    //
    tiles[4][7].n = tiles[3][7].self;                      // stitch # 39 --> # 31
    tiles[4][7].ne = nulltile.self;
    tiles[4][7].e = nulltile.self;
    tiles[4][7].se = nulltile.self;
    tiles[4][7].s = tiles[5][7].self;                      // stitch # 39 --> # 47
    tiles[4][7].sw = tiles[5][6].self;                     // stitch # 39 --> # 46
    tiles[4][7].w = tiles[4][6].self;                      // stitch # 39 --> # 38
    tiles[4][7].nw = tiles[3][6].self;                     // stitch # 39 --> # 30
// init (step 2) for row 5:

    //
    // stitch (init step 2) for [ ROW 5 | COL 0 ]:
    //
    tiles[5][0].n = tiles[4][0].self;                      // stitch # 40 --> # 32
    tiles[5][0].ne = tiles[4][1].self;                     // stitch # 40 --> # 33
    tiles[5][0].e = tiles[5][1].self;                      // stitch # 40 --> # 41
    tiles[5][0].se = tiles[6][1].self;                     // stitch # 40 --> # 49
    tiles[5][0].s = tiles[6][0].self;                      // stitch # 40 --> # 48
    tiles[5][0].sw = nulltile.self;
    tiles[5][0].w = nulltile.self;
    tiles[5][0].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 5 | COL 1 ]:
    //
    tiles[5][1].n = tiles[4][1].self;                      // stitch # 41 --> # 33
    tiles[5][1].ne = tiles[4][2].self;                     // stitch # 41 --> # 34
    tiles[5][1].e = tiles[5][2].self;                      // stitch # 41 --> # 42
    tiles[5][1].se = tiles[6][2].self;                     // stitch # 41 --> # 50
    tiles[5][1].s = tiles[6][1].self;                      // stitch # 41 --> # 49
    tiles[5][1].sw = tiles[6][0].self;                     // stitch # 41 --> # 48
    tiles[5][1].w = tiles[5][0].self;                      // stitch # 41 --> # 40
    tiles[5][1].nw = tiles[4][0].self;                     // stitch # 41 --> # 32

    //
    // stitch (init step 2) for [ ROW 5 | COL 2 ]:
    //
    tiles[5][2].n = tiles[4][2].self;                      // stitch # 42 --> # 34
    tiles[5][2].ne = tiles[4][3].self;                     // stitch # 42 --> # 35
    tiles[5][2].e = tiles[5][3].self;                      // stitch # 42 --> # 43
    tiles[5][2].se = tiles[6][3].self;                     // stitch # 42 --> # 51
    tiles[5][2].s = tiles[6][2].self;                      // stitch # 42 --> # 50
    tiles[5][2].sw = tiles[6][1].self;                     // stitch # 42 --> # 49
    tiles[5][2].w = tiles[5][1].self;                      // stitch # 42 --> # 41
    tiles[5][2].nw = tiles[4][1].self;                     // stitch # 42 --> # 33

    //
    // stitch (init step 2) for [ ROW 5 | COL 3 ]:
    //
    tiles[5][3].n = tiles[4][3].self;                      // stitch # 43 --> # 35
    tiles[5][3].ne = tiles[4][4].self;                     // stitch # 43 --> # 36
    tiles[5][3].e = tiles[5][4].self;                      // stitch # 43 --> # 44
    tiles[5][3].se = tiles[6][4].self;                     // stitch # 43 --> # 52
    tiles[5][3].s = tiles[6][3].self;                      // stitch # 43 --> # 51
    tiles[5][3].sw = tiles[6][2].self;                     // stitch # 43 --> # 50
    tiles[5][3].w = tiles[5][2].self;                      // stitch # 43 --> # 42
    tiles[5][3].nw = tiles[4][2].self;                     // stitch # 43 --> # 34

    //
    // stitch (init step 2) for [ ROW 5 | COL 4 ]:
    //
    tiles[5][4].n = tiles[4][4].self;                      // stitch # 44 --> # 36
    tiles[5][4].ne = tiles[4][5].self;                     // stitch # 44 --> # 37
    tiles[5][4].e = tiles[5][5].self;                      // stitch # 44 --> # 45
    tiles[5][4].se = tiles[6][5].self;                     // stitch # 44 --> # 53
    tiles[5][4].s = tiles[6][4].self;                      // stitch # 44 --> # 52
    tiles[5][4].sw = tiles[6][3].self;                     // stitch # 44 --> # 51
    tiles[5][4].w = tiles[5][3].self;                      // stitch # 44 --> # 43
    tiles[5][4].nw = tiles[4][3].self;                     // stitch # 44 --> # 35

    //
    // stitch (init step 2) for [ ROW 5 | COL 5 ]:
    //
    tiles[5][5].n = tiles[4][5].self;                      // stitch # 45 --> # 37
    tiles[5][5].ne = tiles[4][6].self;                     // stitch # 45 --> # 38
    tiles[5][5].e = tiles[5][6].self;                      // stitch # 45 --> # 46
    tiles[5][5].se = tiles[6][6].self;                     // stitch # 45 --> # 54
    tiles[5][5].s = tiles[6][5].self;                      // stitch # 45 --> # 53
    tiles[5][5].sw = tiles[6][4].self;                     // stitch # 45 --> # 52
    tiles[5][5].w = tiles[5][4].self;                      // stitch # 45 --> # 44
    tiles[5][5].nw = tiles[4][4].self;                     // stitch # 45 --> # 36

    //
    // stitch (init step 2) for [ ROW 5 | COL 6 ]:
    //
    tiles[5][6].n = tiles[4][6].self;                      // stitch # 46 --> # 38
    tiles[5][6].ne = tiles[4][7].self;                     // stitch # 46 --> # 39
    tiles[5][6].e = tiles[5][7].self;                      // stitch # 46 --> # 47
    tiles[5][6].se = tiles[6][7].self;                     // stitch # 46 --> # 55
    tiles[5][6].s = tiles[6][6].self;                      // stitch # 46 --> # 54
    tiles[5][6].sw = tiles[6][5].self;                     // stitch # 46 --> # 53
    tiles[5][6].w = tiles[5][5].self;                      // stitch # 46 --> # 45
    tiles[5][6].nw = tiles[4][5].self;                     // stitch # 46 --> # 37

    //
    // stitch (init step 2) for [ ROW 5 | COL 7 ]:
    //
    tiles[5][7].n = tiles[4][7].self;                      // stitch # 47 --> # 39
    tiles[5][7].ne = nulltile.self;
    tiles[5][7].e = nulltile.self;
    tiles[5][7].se = nulltile.self;
    tiles[5][7].s = tiles[6][7].self;                      // stitch # 47 --> # 55
    tiles[5][7].sw = tiles[6][6].self;                     // stitch # 47 --> # 54
    tiles[5][7].w = tiles[5][6].self;                      // stitch # 47 --> # 46
    tiles[5][7].nw = tiles[4][6].self;                     // stitch # 47 --> # 38
// init (step 2) for row 6:

    //
    // stitch (init step 2) for [ ROW 6 | COL 0 ]:
    //
    tiles[6][0].n = tiles[5][0].self;                      // stitch # 48 --> # 40
    tiles[6][0].ne = tiles[5][1].self;                     // stitch # 48 --> # 41
    tiles[6][0].e = tiles[6][1].self;                      // stitch # 48 --> # 49
    tiles[6][0].se = tiles[7][1].self;                     // stitch # 48 --> # 57
    tiles[6][0].s = tiles[7][0].self;                      // stitch # 48 --> # 56
    tiles[6][0].sw = nulltile.self;
    tiles[6][0].w = nulltile.self;
    tiles[6][0].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 6 | COL 1 ]:
    //
    tiles[6][1].n = tiles[5][1].self;                      // stitch # 49 --> # 41
    tiles[6][1].ne = tiles[5][2].self;                     // stitch # 49 --> # 42
    tiles[6][1].e = tiles[6][2].self;                      // stitch # 49 --> # 50
    tiles[6][1].se = tiles[7][2].self;                     // stitch # 49 --> # 58
    tiles[6][1].s = tiles[7][1].self;                      // stitch # 49 --> # 57
    tiles[6][1].sw = tiles[7][0].self;                     // stitch # 49 --> # 56
    tiles[6][1].w = tiles[6][0].self;                      // stitch # 49 --> # 48
    tiles[6][1].nw = tiles[5][0].self;                     // stitch # 49 --> # 40

    //
    // stitch (init step 2) for [ ROW 6 | COL 2 ]:
    //
    tiles[6][2].n = tiles[5][2].self;                      // stitch # 50 --> # 42
    tiles[6][2].ne = tiles[5][3].self;                     // stitch # 50 --> # 43
    tiles[6][2].e = tiles[6][3].self;                      // stitch # 50 --> # 51
    tiles[6][2].se = tiles[7][3].self;                     // stitch # 50 --> # 59
    tiles[6][2].s = tiles[7][2].self;                      // stitch # 50 --> # 58
    tiles[6][2].sw = tiles[7][1].self;                     // stitch # 50 --> # 57
    tiles[6][2].w = tiles[6][1].self;                      // stitch # 50 --> # 49
    tiles[6][2].nw = tiles[5][1].self;                     // stitch # 50 --> # 41

    //
    // stitch (init step 2) for [ ROW 6 | COL 3 ]:
    //
    tiles[6][3].n = tiles[5][3].self;                      // stitch # 51 --> # 43
    tiles[6][3].ne = tiles[5][4].self;                     // stitch # 51 --> # 44
    tiles[6][3].e = tiles[6][4].self;                      // stitch # 51 --> # 52
    tiles[6][3].se = tiles[7][4].self;                     // stitch # 51 --> # 60
    tiles[6][3].s = tiles[7][3].self;                      // stitch # 51 --> # 59
    tiles[6][3].sw = tiles[7][2].self;                     // stitch # 51 --> # 58
    tiles[6][3].w = tiles[6][2].self;                      // stitch # 51 --> # 50
    tiles[6][3].nw = tiles[5][2].self;                     // stitch # 51 --> # 42

    //
    // stitch (init step 2) for [ ROW 6 | COL 4 ]:
    //
    tiles[6][4].n = tiles[5][4].self;                      // stitch # 52 --> # 44
    tiles[6][4].ne = tiles[5][5].self;                     // stitch # 52 --> # 45
    tiles[6][4].e = tiles[6][5].self;                      // stitch # 52 --> # 53
    tiles[6][4].se = tiles[7][5].self;                     // stitch # 52 --> # 61
    tiles[6][4].s = tiles[7][4].self;                      // stitch # 52 --> # 60
    tiles[6][4].sw = tiles[7][3].self;                     // stitch # 52 --> # 59
    tiles[6][4].w = tiles[6][3].self;                      // stitch # 52 --> # 51
    tiles[6][4].nw = tiles[5][3].self;                     // stitch # 52 --> # 43

    //
    // stitch (init step 2) for [ ROW 6 | COL 5 ]:
    //
    tiles[6][5].n = tiles[5][5].self;                      // stitch # 53 --> # 45
    tiles[6][5].ne = tiles[5][6].self;                     // stitch # 53 --> # 46
    tiles[6][5].e = tiles[6][6].self;                      // stitch # 53 --> # 54
    tiles[6][5].se = tiles[7][6].self;                     // stitch # 53 --> # 62
    tiles[6][5].s = tiles[7][5].self;                      // stitch # 53 --> # 61
    tiles[6][5].sw = tiles[7][4].self;                     // stitch # 53 --> # 60
    tiles[6][5].w = tiles[6][4].self;                      // stitch # 53 --> # 52
    tiles[6][5].nw = tiles[5][4].self;                     // stitch # 53 --> # 44

    //
    // stitch (init step 2) for [ ROW 6 | COL 6 ]:
    //
    tiles[6][6].n = tiles[5][6].self;                      // stitch # 54 --> # 46
    tiles[6][6].ne = tiles[5][7].self;                     // stitch # 54 --> # 47
    tiles[6][6].e = tiles[6][7].self;                      // stitch # 54 --> # 55
    tiles[6][6].se = tiles[7][7].self;                     // stitch # 54 --> # 63
    tiles[6][6].s = tiles[7][6].self;                      // stitch # 54 --> # 62
    tiles[6][6].sw = tiles[7][5].self;                     // stitch # 54 --> # 61
    tiles[6][6].w = tiles[6][5].self;                      // stitch # 54 --> # 53
    tiles[6][6].nw = tiles[5][5].self;                     // stitch # 54 --> # 45

    //
    // stitch (init step 2) for [ ROW 6 | COL 7 ]:
    //
    tiles[6][7].n = tiles[5][7].self;                      // stitch # 55 --> # 47
    tiles[6][7].ne = nulltile.self;
    tiles[6][7].e = nulltile.self;
    tiles[6][7].se = nulltile.self;
    tiles[6][7].s = tiles[7][7].self;                      // stitch # 55 --> # 63
    tiles[6][7].sw = tiles[7][6].self;                     // stitch # 55 --> # 62
    tiles[6][7].w = tiles[6][6].self;                      // stitch # 55 --> # 54
    tiles[6][7].nw = tiles[5][6].self;                     // stitch # 55 --> # 46
// init (step 2) for row 7:

    //
    // stitch (init step 2) for [ ROW 7 | COL 0 ]:
    //
    tiles[7][0].n = tiles[6][0].self;                      // stitch # 56 --> # 48
    tiles[7][0].ne = tiles[6][1].self;                     // stitch # 56 --> # 49
    tiles[7][0].e = tiles[7][1].self;                      // stitch # 56 --> # 57
    tiles[7][0].se = nulltile.self;
    tiles[7][0].s = nulltile.self;
    tiles[7][0].sw = nulltile.self;
    tiles[7][0].w = nulltile.self;
    tiles[7][0].nw = nulltile.self;

    //
    // stitch (init step 2) for [ ROW 7 | COL 1 ]:
    //
    tiles[7][1].n = tiles[6][1].self;                      // stitch # 57 --> # 49
    tiles[7][1].ne = tiles[6][2].self;                     // stitch # 57 --> # 50
    tiles[7][1].e = tiles[7][2].self;                      // stitch # 57 --> # 58
    tiles[7][1].se = nulltile.self;
    tiles[7][1].s = nulltile.self;
    tiles[7][1].sw = nulltile.self;
    tiles[7][1].w = tiles[7][0].self;                      // stitch # 57 --> # 56
    tiles[7][1].nw = tiles[6][0].self;                     // stitch # 57 --> # 48

    //
    // stitch (init step 2) for [ ROW 7 | COL 2 ]:
    //
    tiles[7][2].n = tiles[6][2].self;                      // stitch # 58 --> # 50
    tiles[7][2].ne = tiles[6][3].self;                     // stitch # 58 --> # 51
    tiles[7][2].e = tiles[7][3].self;                      // stitch # 58 --> # 59
    tiles[7][2].se = nulltile.self;
    tiles[7][2].s = nulltile.self;
    tiles[7][2].sw = nulltile.self;
    tiles[7][2].w = tiles[7][1].self;                      // stitch # 58 --> # 57
    tiles[7][2].nw = tiles[6][1].self;                     // stitch # 58 --> # 49

    //
    // stitch (init step 2) for [ ROW 7 | COL 3 ]:
    //
    tiles[7][3].n = tiles[6][3].self;                      // stitch # 59 --> # 51
    tiles[7][3].ne = tiles[6][4].self;                     // stitch # 59 --> # 52
    tiles[7][3].e = tiles[7][4].self;                      // stitch # 59 --> # 60
    tiles[7][3].se = nulltile.self;
    tiles[7][3].s = nulltile.self;
    tiles[7][3].sw = nulltile.self;
    tiles[7][3].w = tiles[7][2].self;                      // stitch # 59 --> # 58
    tiles[7][3].nw = tiles[6][2].self;                     // stitch # 59 --> # 50

    //
    // stitch (init step 2) for [ ROW 7 | COL 4 ]:
    //
    tiles[7][4].n = tiles[6][4].self;                      // stitch # 60 --> # 52
    tiles[7][4].ne = tiles[6][5].self;                     // stitch # 60 --> # 53
    tiles[7][4].e = tiles[7][5].self;                      // stitch # 60 --> # 61
    tiles[7][4].se = nulltile.self;
    tiles[7][4].s = nulltile.self;
    tiles[7][4].sw = nulltile.self;
    tiles[7][4].w = tiles[7][3].self;                      // stitch # 60 --> # 59
    tiles[7][4].nw = tiles[6][3].self;                     // stitch # 60 --> # 51

    //
    // stitch (init step 2) for [ ROW 7 | COL 5 ]:
    //
    tiles[7][5].n = tiles[6][5].self;                      // stitch # 61 --> # 53
    tiles[7][5].ne = tiles[6][6].self;                     // stitch # 61 --> # 54
    tiles[7][5].e = tiles[7][6].self;                      // stitch # 61 --> # 62
    tiles[7][5].se = nulltile.self;
    tiles[7][5].s = nulltile.self;
    tiles[7][5].sw = nulltile.self;
    tiles[7][5].w = tiles[7][4].self;                      // stitch # 61 --> # 60
    tiles[7][5].nw = tiles[6][4].self;                     // stitch # 61 --> # 52

    //
    // stitch (init step 2) for [ ROW 7 | COL 6 ]:
    //
    tiles[7][6].n = tiles[6][6].self;                      // stitch # 62 --> # 54
    tiles[7][6].ne = tiles[6][7].self;                     // stitch # 62 --> # 55
    tiles[7][6].e = tiles[7][7].self;                      // stitch # 62 --> # 63
    tiles[7][6].se = nulltile.self;
    tiles[7][6].s = nulltile.self;
    tiles[7][6].sw = nulltile.self;
    tiles[7][6].w = tiles[7][5].self;                      // stitch # 62 --> # 61
    tiles[7][6].nw = tiles[6][5].self;                     // stitch # 62 --> # 53

    //
    // stitch (init step 2) for [ ROW 7 | COL 7 ]:
    //
    tiles[7][7].n = tiles[6][7].self;                      // stitch # 63 --> # 55
    tiles[7][7].ne = nulltile.self;
    tiles[7][7].e = nulltile.self;
    tiles[7][7].se = nulltile.self;
    tiles[7][7].s = nulltile.self;
    tiles[7][7].sw = nulltile.self;
    tiles[7][7].w = tiles[7][6].self;                      // stitch # 63 --> # 62
    tiles[7][7].nw = tiles[6][6].self;                     // stitch # 63 --> # 54

//
// Generating payload TODOs
//


    //  TODO: tiles[0][0].payload = new SAMClib::ROOK(team=0)
    //  TODO: tiles[0][1].payload = new SAMClib::PAWN(team=0)
    //  TODO: tiles[0][2].payload = new SAMClib::BISHOP(team=0)
    //  TODO: tiles[0][3].payload = new SAMClib::QUEEN(team=0)
    //  TODO: tiles[0][4].payload = new SAMClib::KING(team=0)
    //  TODO: tiles[0][5].payload = new SAMClib::BISHOP(team=0)
    //  TODO: tiles[0][6].payload = new SAMClib::PAWN(team=0)
    //  TODO: tiles[0][7].payload = new SAMClib::ROOK(team=0)

    //  TODO: tiles[1][0].payload = new SAMClib::ROOK(team=0)
    //  TODO: tiles[1][1].payload = new SAMClib::PAWN(team=0)
    //  TODO: tiles[1][2].payload = new SAMClib::BISHOP(team=0)
    //  TODO: tiles[1][3].payload = new SAMClib::QUEEN(team=0)
    //  TODO: tiles[1][4].payload = new SAMClib::KING(team=0)
    //  TODO: tiles[1][5].payload = new SAMClib::BISHOP(team=0)
    //  TODO: tiles[1][6].payload = new SAMClib::PAWN(team=0)
    //  TODO: tiles[1][7].payload = new SAMClib::ROOK(team=0)

    //  TODO: tiles[2][0].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[2][1].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[2][2].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[2][3].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[2][4].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[2][5].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[2][6].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[2][7].payload = new SAMClib::BLANK_PIECE

    //  TODO: tiles[3][0].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[3][1].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[3][2].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[3][3].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[3][4].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[3][5].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[3][6].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[3][7].payload = new SAMClib::BLANK_PIECE

    //  TODO: tiles[4][0].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[4][1].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[4][2].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[4][3].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[4][4].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[4][5].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[4][6].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[4][7].payload = new SAMClib::BLANK_PIECE

    //  TODO: tiles[5][0].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[5][1].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[5][2].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[5][3].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[5][4].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[5][5].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[5][6].payload = new SAMClib::BLANK_PIECE
    //  TODO: tiles[5][7].payload = new SAMClib::BLANK_PIECE

    //  TODO: tiles[6][0].payload = new SAMClib::ROOK(team=1)
    //  TODO: tiles[6][1].payload = new SAMClib::PAWN(team=1)
    //  TODO: tiles[6][2].payload = new SAMClib::BISHOP(team=1)
    //  TODO: tiles[6][3].payload = new SAMClib::QUEEN(team=1)
    //  TODO: tiles[6][4].payload = new SAMClib::KING(team=1)
    //  TODO: tiles[6][5].payload = new SAMClib::BISHOP(team=1)
    //  TODO: tiles[6][6].payload = new SAMClib::PAWN(team=1)
    //  TODO: tiles[6][7].payload = new SAMClib::ROOK(team=1)

    //  TODO: tiles[7][0].payload = new SAMClib::ROOK(team=1)
    //  TODO: tiles[7][1].payload = new SAMClib::PAWN(team=1)
    //  TODO: tiles[7][2].payload = new SAMClib::BISHOP(team=1)
    //  TODO: tiles[7][3].payload = new SAMClib::QUEEN(team=1)
    //  TODO: tiles[7][4].payload = new SAMClib::KING(team=1)
    //  TODO: tiles[7][5].payload = new SAMClib::BISHOP(team=1)
    //  TODO: tiles[7][6].payload = new SAMClib::PAWN(team=1)
    //  TODO: tiles[7][7].payload = new SAMClib::ROOK(team=1)


    cout << "Hello, World!" << endl;
    return 0;
}